/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TextualDataModelGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class DataModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.DataModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDataModelKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cDescriptionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_2_1_2_0 = (RuleCall)cDescriptionAssignment_2_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cLocalesKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_2_1 = (Keyword)cGroup_2_2.eContents().get(1);
		private final Assignment cLocalesAssignment_2_2_2 = (Assignment)cGroup_2_2.eContents().get(2);
		private final RuleCall cLocalesIDTerminalRuleCall_2_2_2_0 = (RuleCall)cLocalesAssignment_2_2_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_2_3 = (Keyword)cGroup_2_2.eContents().get(3);
		private final Assignment cLocalizationsAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_2_3_0 = (RuleCall)cLocalizationsAssignment_2_3.eContents().get(0);
		private final Assignment cEntitiesAssignment_2_4 = (Assignment)cGroup_2.eContents().get(4);
		private final RuleCall cEntitiesEntityParserRuleCall_2_4_0 = (RuleCall)cEntitiesAssignment_2_4.eContents().get(0);
		private final Assignment cRelationshipsAssignment_2_5 = (Assignment)cGroup_2.eContents().get(5);
		private final RuleCall cRelationshipsRelationshipParserRuleCall_2_5_0 = (RuleCall)cRelationshipsAssignment_2_5.eContents().get(0);
		private final Assignment cDataTypesAssignment_2_6 = (Assignment)cGroup_2.eContents().get(6);
		private final RuleCall cDataTypesDataTypeParserRuleCall_2_6_0 = (RuleCall)cDataTypesAssignment_2_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_7 = (Keyword)cGroup_2.eContents().get(7);
		
		//DataModel returns DataModel:
		//    'DataModel'
		//    name=ElementName
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        ('@locales' '(' locales+=ID* ')' )?
		//        localizations+=Localization*
		//        entities+=Entity*
		//        relationships+=Relationship*
		//        dataTypes+=DataType*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'DataModel'
		//name=ElementName
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    ('@locales' '(' locales+=ID* ')' )?
		//    localizations+=Localization*
		//    entities+=Entity*
		//    relationships+=Relationship*
		//    dataTypes+=DataType*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'DataModel'
		public Keyword getDataModelKeyword_0() { return cDataModelKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    ('@locales' '(' locales+=ID* ')' )?
		//    localizations+=Localization*
		//    entities+=Entity*
		//    relationships+=Relationship*
		//    dataTypes+=DataType*
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_2_1_0() { return cDescriptionKeyword_2_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_1() { return cLeftParenthesisKeyword_2_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_2_1_2() { return cDescriptionAssignment_2_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_2_1_2_0() { return cDescriptionTextParserRuleCall_2_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_3() { return cRightParenthesisKeyword_2_1_3; }
		
		//('@locales' '(' locales+=ID* ')' )?
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'@locales'
		public Keyword getLocalesKeyword_2_2_0() { return cLocalesKeyword_2_2_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_2_1() { return cLeftParenthesisKeyword_2_2_1; }
		
		//locales+=ID*
		public Assignment getLocalesAssignment_2_2_2() { return cLocalesAssignment_2_2_2; }
		
		//ID
		public RuleCall getLocalesIDTerminalRuleCall_2_2_2_0() { return cLocalesIDTerminalRuleCall_2_2_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_2_3() { return cRightParenthesisKeyword_2_2_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_2_3() { return cLocalizationsAssignment_2_3; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_2_3_0() { return cLocalizationsLocalizationParserRuleCall_2_3_0; }
		
		//entities+=Entity*
		public Assignment getEntitiesAssignment_2_4() { return cEntitiesAssignment_2_4; }
		
		//Entity
		public RuleCall getEntitiesEntityParserRuleCall_2_4_0() { return cEntitiesEntityParserRuleCall_2_4_0; }
		
		//relationships+=Relationship*
		public Assignment getRelationshipsAssignment_2_5() { return cRelationshipsAssignment_2_5; }
		
		//Relationship
		public RuleCall getRelationshipsRelationshipParserRuleCall_2_5_0() { return cRelationshipsRelationshipParserRuleCall_2_5_0; }
		
		//dataTypes+=DataType*
		public Assignment getDataTypesAssignment_2_6() { return cDataTypesAssignment_2_6; }
		
		//DataType
		public RuleCall getDataTypesDataTypeParserRuleCall_2_6_0() { return cDataTypesDataTypeParserRuleCall_2_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_7() { return cRightCurlyBracketKeyword_2_7; }
	}
	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftSquareBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cKindAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cKindEntityKindEnumRuleCall_2_1_0 = (RuleCall)cKindAssignment_2_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cColonColonKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cGeneralsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cGeneralsEntityCrossReference_3_1_0 = (CrossReference)cGeneralsAssignment_3_1.eContents().get(0);
		private final RuleCall cGeneralsEntityElementNameParserRuleCall_3_1_0_1 = (RuleCall)cGeneralsEntityCrossReference_3_1_0.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cDescriptionKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1_1 = (Keyword)cGroup_4_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_4_1_2 = (Assignment)cGroup_4_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_4_1_2_0 = (RuleCall)cDescriptionAssignment_4_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_1_3 = (Keyword)cGroup_4_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_4_2_0 = (RuleCall)cLocalizationsAssignment_4_2.eContents().get(0);
		private final Assignment cAttributesAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cAttributesAttributeParserRuleCall_4_3_0 = (RuleCall)cAttributesAssignment_4_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		
		//Entity returns Entity:
		//    'Entity'
		//    name=ElementName
		//    ('[' kind=EntityKind ']')?
		//    ('::' generals+=[Entity|ElementName]+)?
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//        attributes+=Attribute*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'Entity'
		//name=ElementName
		//('[' kind=EntityKind ']')?
		//('::' generals+=[Entity|ElementName]+)?
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    attributes+=Attribute*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'Entity'
		public Keyword getEntityKeyword_0() { return cEntityKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('[' kind=EntityKind ']')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_2_0() { return cLeftSquareBracketKeyword_2_0; }
		
		//kind=EntityKind
		public Assignment getKindAssignment_2_1() { return cKindAssignment_2_1; }
		
		//EntityKind
		public RuleCall getKindEntityKindEnumRuleCall_2_1_0() { return cKindEntityKindEnumRuleCall_2_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_2_2() { return cRightSquareBracketKeyword_2_2; }
		
		//('::' generals+=[Entity|ElementName]+)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'::'
		public Keyword getColonColonKeyword_3_0() { return cColonColonKeyword_3_0; }
		
		//generals+=[Entity|ElementName]+
		public Assignment getGeneralsAssignment_3_1() { return cGeneralsAssignment_3_1; }
		
		//[Entity|ElementName]
		public CrossReference getGeneralsEntityCrossReference_3_1_0() { return cGeneralsEntityCrossReference_3_1_0; }
		
		//ElementName
		public RuleCall getGeneralsEntityElementNameParserRuleCall_3_1_0_1() { return cGeneralsEntityElementNameParserRuleCall_3_1_0_1; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    attributes+=Attribute*
		//'}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_4_1_0() { return cDescriptionKeyword_4_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1_1() { return cLeftParenthesisKeyword_4_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_4_1_2() { return cDescriptionAssignment_4_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_4_1_2_0() { return cDescriptionTextParserRuleCall_4_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_1_3() { return cRightParenthesisKeyword_4_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_4_2() { return cLocalizationsAssignment_4_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_4_2_0() { return cLocalizationsLocalizationParserRuleCall_4_2_0; }
		
		//attributes+=Attribute*
		public Assignment getAttributesAssignment_4_3() { return cAttributesAssignment_4_3; }
		
		//Attribute
		public RuleCall getAttributesAttributeParserRuleCall_4_3_0() { return cAttributesAttributeParserRuleCall_4_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
	}
	public class AttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.Attribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameElementNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cDataTypeAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cDataTypeDataTypeCrossReference_1_0 = (CrossReference)cDataTypeAssignment_1.eContents().get(0);
		private final RuleCall cDataTypeDataTypeElementNameParserRuleCall_1_0_1 = (RuleCall)cDataTypeDataTypeCrossReference_1_0.eContents().get(1);
		private final Assignment cLowerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLowerINTTerminalRuleCall_2_0 = (RuleCall)cLowerAssignment_2.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUpperAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUpperUnlimitedNaturalParserRuleCall_4_0 = (RuleCall)cUpperAssignment_4.eContents().get(0);
		private final Assignment cIdentityAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final Keyword cIdentityIdKeyword_5_0 = (Keyword)cIdentityAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cDefaultValueKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cDefaultValueAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cDefaultValueTextParserRuleCall_6_2_0 = (RuleCall)cDefaultValueAssignment_6_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6_3 = (Keyword)cGroup_6.eContents().get(3);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cLeftCurlyBracketKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Group cGroup_7_1 = (Group)cGroup_7.eContents().get(1);
		private final Keyword cDescriptionKeyword_7_1_0 = (Keyword)cGroup_7_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_7_1_1 = (Keyword)cGroup_7_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_7_1_2 = (Assignment)cGroup_7_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_7_1_2_0 = (RuleCall)cDescriptionAssignment_7_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7_1_3 = (Keyword)cGroup_7_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_7_2_0 = (RuleCall)cLocalizationsAssignment_7_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//Attribute returns Attribute:
		//    name=ElementName
		//    dataType=[DataType|ElementName]
		//    lower=INT '..' upper=UnlimitedNatural
		//    (identity?='[id]')?
		//    ('defaultValue' '(' defaultValue=Text ')')?
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ElementName
		//dataType=[DataType|ElementName]
		//lower=INT '..' upper=UnlimitedNatural
		//(identity?='[id]')?
		//('defaultValue' '(' defaultValue=Text ')')?
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//name=ElementName
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_0_0() { return cNameElementNameParserRuleCall_0_0; }
		
		//dataType=[DataType|ElementName]
		public Assignment getDataTypeAssignment_1() { return cDataTypeAssignment_1; }
		
		//[DataType|ElementName]
		public CrossReference getDataTypeDataTypeCrossReference_1_0() { return cDataTypeDataTypeCrossReference_1_0; }
		
		//ElementName
		public RuleCall getDataTypeDataTypeElementNameParserRuleCall_1_0_1() { return cDataTypeDataTypeElementNameParserRuleCall_1_0_1; }
		
		//lower=INT
		public Assignment getLowerAssignment_2() { return cLowerAssignment_2; }
		
		//INT
		public RuleCall getLowerINTTerminalRuleCall_2_0() { return cLowerINTTerminalRuleCall_2_0; }
		
		//'..'
		public Keyword getFullStopFullStopKeyword_3() { return cFullStopFullStopKeyword_3; }
		
		//upper=UnlimitedNatural
		public Assignment getUpperAssignment_4() { return cUpperAssignment_4; }
		
		//UnlimitedNatural
		public RuleCall getUpperUnlimitedNaturalParserRuleCall_4_0() { return cUpperUnlimitedNaturalParserRuleCall_4_0; }
		
		//(identity?='[id]')?
		public Assignment getIdentityAssignment_5() { return cIdentityAssignment_5; }
		
		//'[id]'
		public Keyword getIdentityIdKeyword_5_0() { return cIdentityIdKeyword_5_0; }
		
		//('defaultValue' '(' defaultValue=Text ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'defaultValue'
		public Keyword getDefaultValueKeyword_6_0() { return cDefaultValueKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//defaultValue=Text
		public Assignment getDefaultValueAssignment_6_2() { return cDefaultValueAssignment_6_2; }
		
		//Text
		public RuleCall getDefaultValueTextParserRuleCall_6_2_0() { return cDefaultValueTextParserRuleCall_6_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_3() { return cRightParenthesisKeyword_6_3; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_0() { return cLeftCurlyBracketKeyword_7_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_7_1() { return cGroup_7_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_7_1_0() { return cDescriptionKeyword_7_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_7_1_1() { return cLeftParenthesisKeyword_7_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_7_1_2() { return cDescriptionAssignment_7_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_7_1_2_0() { return cDescriptionTextParserRuleCall_7_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_1_3() { return cRightParenthesisKeyword_7_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_7_2() { return cLocalizationsAssignment_7_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_7_2_0() { return cLocalizationsLocalizationParserRuleCall_7_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_3() { return cRightCurlyBracketKeyword_7_3; }
	}
	public class RelationshipElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.Relationship");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelationshipAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRelationshipKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameElementNameParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cLeftSquareBracketKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cKindAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cKindRelationshipKindEnumRuleCall_3_1_0 = (RuleCall)cKindAssignment_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cGroup_4.eContents().get(1);
		private final Keyword cDescriptionKeyword_4_1_0 = (Keyword)cGroup_4_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1_1 = (Keyword)cGroup_4_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_4_1_2 = (Assignment)cGroup_4_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_4_1_2_0 = (RuleCall)cDescriptionAssignment_4_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4_1_3 = (Keyword)cGroup_4_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_4_2_0 = (RuleCall)cLocalizationsAssignment_4_2.eContents().get(0);
		private final Assignment cEndsAssignment_4_3 = (Assignment)cGroup_4.eContents().get(3);
		private final RuleCall cEndsRelationshipEndParserRuleCall_4_3_0 = (RuleCall)cEndsAssignment_4_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		
		//Relationship returns Relationship:
		//    {Relationship}
		//    'Relationship'
		//    name=ElementName?
		//    ('[' kind=RelationshipKind ']')?
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//        ends+=RelationshipEnd*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//{Relationship}
		//'Relationship'
		//name=ElementName?
		//('[' kind=RelationshipKind ']')?
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    ends+=RelationshipEnd*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//{Relationship}
		public Action getRelationshipAction_0() { return cRelationshipAction_0; }
		
		//'Relationship'
		public Keyword getRelationshipKeyword_1() { return cRelationshipKeyword_1; }
		
		//name=ElementName?
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_2_0() { return cNameElementNameParserRuleCall_2_0; }
		
		//('[' kind=RelationshipKind ']')?
		public Group getGroup_3() { return cGroup_3; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_0() { return cLeftSquareBracketKeyword_3_0; }
		
		//kind=RelationshipKind
		public Assignment getKindAssignment_3_1() { return cKindAssignment_3_1; }
		
		//RelationshipKind
		public RuleCall getKindRelationshipKindEnumRuleCall_3_1_0() { return cKindRelationshipKindEnumRuleCall_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_2() { return cRightSquareBracketKeyword_3_2; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    ends+=RelationshipEnd*
		//'}')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_0() { return cLeftCurlyBracketKeyword_4_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_4_1() { return cGroup_4_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_4_1_0() { return cDescriptionKeyword_4_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1_1() { return cLeftParenthesisKeyword_4_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_4_1_2() { return cDescriptionAssignment_4_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_4_1_2_0() { return cDescriptionTextParserRuleCall_4_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_1_3() { return cRightParenthesisKeyword_4_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_4_2() { return cLocalizationsAssignment_4_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_4_2_0() { return cLocalizationsLocalizationParserRuleCall_4_2_0; }
		
		//ends+=RelationshipEnd*
		public Assignment getEndsAssignment_4_3() { return cEndsAssignment_4_3; }
		
		//RelationshipEnd
		public RuleCall getEndsRelationshipEndParserRuleCall_4_3_0() { return cEndsRelationshipEndParserRuleCall_4_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
	}
	public class RelationshipEndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.RelationshipEnd");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameElementNameParserRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cEntityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cEntityEntityCrossReference_1_0 = (CrossReference)cEntityAssignment_1.eContents().get(0);
		private final RuleCall cEntityEntityElementNameParserRuleCall_1_0_1 = (RuleCall)cEntityEntityCrossReference_1_0.eContents().get(1);
		private final Assignment cLowerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLowerINTTerminalRuleCall_2_0 = (RuleCall)cLowerAssignment_2.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cUpperAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cUpperUnlimitedNaturalParserRuleCall_4_0 = (RuleCall)cUpperAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Group cGroup_5_1 = (Group)cGroup_5.eContents().get(1);
		private final Keyword cDescriptionKeyword_5_1_0 = (Keyword)cGroup_5_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1_1 = (Keyword)cGroup_5_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_5_1_2 = (Assignment)cGroup_5_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_5_1_2_0 = (RuleCall)cDescriptionAssignment_5_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5_1_3 = (Keyword)cGroup_5_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_5_2_0 = (RuleCall)cLocalizationsAssignment_5_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		
		//RelationshipEnd returns RelationshipEnd:
		//    name=ElementName?
		//    entity=[Entity|ElementName]
		//    lower=INT '..' upper=UnlimitedNatural
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ElementName?
		//entity=[Entity|ElementName]
		//lower=INT '..' upper=UnlimitedNatural
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//name=ElementName?
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_0_0() { return cNameElementNameParserRuleCall_0_0; }
		
		//entity=[Entity|ElementName]
		public Assignment getEntityAssignment_1() { return cEntityAssignment_1; }
		
		//[Entity|ElementName]
		public CrossReference getEntityEntityCrossReference_1_0() { return cEntityEntityCrossReference_1_0; }
		
		//ElementName
		public RuleCall getEntityEntityElementNameParserRuleCall_1_0_1() { return cEntityEntityElementNameParserRuleCall_1_0_1; }
		
		//lower=INT
		public Assignment getLowerAssignment_2() { return cLowerAssignment_2; }
		
		//INT
		public RuleCall getLowerINTTerminalRuleCall_2_0() { return cLowerINTTerminalRuleCall_2_0; }
		
		//'..'
		public Keyword getFullStopFullStopKeyword_3() { return cFullStopFullStopKeyword_3; }
		
		//upper=UnlimitedNatural
		public Assignment getUpperAssignment_4() { return cUpperAssignment_4; }
		
		//UnlimitedNatural
		public RuleCall getUpperUnlimitedNaturalParserRuleCall_4_0() { return cUpperUnlimitedNaturalParserRuleCall_4_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5_0() { return cLeftCurlyBracketKeyword_5_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_5_1() { return cGroup_5_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_5_1_0() { return cDescriptionKeyword_5_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1_1() { return cLeftParenthesisKeyword_5_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_5_1_2() { return cDescriptionAssignment_5_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_5_1_2_0() { return cDescriptionTextParserRuleCall_5_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_1_3() { return cRightParenthesisKeyword_5_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_5_2() { return cLocalizationsAssignment_5_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_5_2_0() { return cLocalizationsLocalizationParserRuleCall_5_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5_3() { return cRightCurlyBracketKeyword_5_3; }
	}
	public class DataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.DataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBooleanTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNumericTypeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDateTypeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDateTimeTypeParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cUuidTypeParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//DataType returns DataType:
		//    BooleanType | StringType | NumericType | DateType | DateTimeType | UuidType;
		@Override public ParserRule getRule() { return rule; }
		
		//BooleanType | StringType | NumericType | DateType | DateTimeType | UuidType
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//BooleanType
		public RuleCall getBooleanTypeParserRuleCall_0() { return cBooleanTypeParserRuleCall_0; }
		
		//StringType
		public RuleCall getStringTypeParserRuleCall_1() { return cStringTypeParserRuleCall_1; }
		
		//NumericType
		public RuleCall getNumericTypeParserRuleCall_2() { return cNumericTypeParserRuleCall_2; }
		
		//DateType
		public RuleCall getDateTypeParserRuleCall_3() { return cDateTypeParserRuleCall_3; }
		
		//DateTimeType
		public RuleCall getDateTimeTypeParserRuleCall_4() { return cDateTimeTypeParserRuleCall_4; }
		
		//UuidType
		public RuleCall getUuidTypeParserRuleCall_5() { return cUuidTypeParserRuleCall_5; }
	}
	public class BooleanTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.BooleanType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBooleanTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cDescriptionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_2_1_2_0 = (RuleCall)cDescriptionAssignment_2_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_2_2_0 = (RuleCall)cLocalizationsAssignment_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//BooleanType returns BooleanType:
		//    'BooleanType'
		//    name=ElementName
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'BooleanType'
		//name=ElementName
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'BooleanType'
		public Keyword getBooleanTypeKeyword_0() { return cBooleanTypeKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_2_1_0() { return cDescriptionKeyword_2_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_1() { return cLeftParenthesisKeyword_2_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_2_1_2() { return cDescriptionAssignment_2_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_2_1_2_0() { return cDescriptionTextParserRuleCall_2_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_3() { return cRightParenthesisKeyword_2_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_2_2() { return cLocalizationsAssignment_2_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_2_2_0() { return cLocalizationsLocalizationParserRuleCall_2_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}
	public class StringTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.StringType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStringTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cDescriptionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_2_1_2_0 = (RuleCall)cDescriptionAssignment_2_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_2_2_0 = (RuleCall)cLocalizationsAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cLengthKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cLengthAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cLengthINTTerminalRuleCall_2_3_1_0 = (RuleCall)cLengthAssignment_2_3_1.eContents().get(0);
		private final Group cGroup_2_4 = (Group)cGroup_2.eContents().get(4);
		private final Keyword cMinLengthKeyword_2_4_0 = (Keyword)cGroup_2_4.eContents().get(0);
		private final Assignment cMinLengthAssignment_2_4_1 = (Assignment)cGroup_2_4.eContents().get(1);
		private final RuleCall cMinLengthINTTerminalRuleCall_2_4_1_0 = (RuleCall)cMinLengthAssignment_2_4_1.eContents().get(0);
		private final Group cGroup_2_5 = (Group)cGroup_2.eContents().get(5);
		private final Keyword cMaxLengthKeyword_2_5_0 = (Keyword)cGroup_2_5.eContents().get(0);
		private final Assignment cMaxLengthAssignment_2_5_1 = (Assignment)cGroup_2_5.eContents().get(1);
		private final RuleCall cMaxLengthINTTerminalRuleCall_2_5_1_0 = (RuleCall)cMaxLengthAssignment_2_5_1.eContents().get(0);
		private final Group cGroup_2_6 = (Group)cGroup_2.eContents().get(6);
		private final Keyword cPatternKeyword_2_6_0 = (Keyword)cGroup_2_6.eContents().get(0);
		private final Assignment cPatternAssignment_2_6_1 = (Assignment)cGroup_2_6.eContents().get(1);
		private final RuleCall cPatternTextParserRuleCall_2_6_1_0 = (RuleCall)cPatternAssignment_2_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_7 = (Keyword)cGroup_2.eContents().get(7);
		
		//StringType returns StringType:
		//    'StringType'
		//    name=ElementName
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//        ('length' length=INT)?
		//        ('minLength' minLength=INT)?
		//        ('maxLength' maxLength=INT)?
		//        ('pattern' pattern=Text)?
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'StringType'
		//name=ElementName
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    ('length' length=INT)?
		//    ('minLength' minLength=INT)?
		//    ('maxLength' maxLength=INT)?
		//    ('pattern' pattern=Text)?
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'StringType'
		public Keyword getStringTypeKeyword_0() { return cStringTypeKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    ('length' length=INT)?
		//    ('minLength' minLength=INT)?
		//    ('maxLength' maxLength=INT)?
		//    ('pattern' pattern=Text)?
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_2_1_0() { return cDescriptionKeyword_2_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_1() { return cLeftParenthesisKeyword_2_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_2_1_2() { return cDescriptionAssignment_2_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_2_1_2_0() { return cDescriptionTextParserRuleCall_2_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_3() { return cRightParenthesisKeyword_2_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_2_2() { return cLocalizationsAssignment_2_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_2_2_0() { return cLocalizationsLocalizationParserRuleCall_2_2_0; }
		
		//('length' length=INT)?
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//'length'
		public Keyword getLengthKeyword_2_3_0() { return cLengthKeyword_2_3_0; }
		
		//length=INT
		public Assignment getLengthAssignment_2_3_1() { return cLengthAssignment_2_3_1; }
		
		//INT
		public RuleCall getLengthINTTerminalRuleCall_2_3_1_0() { return cLengthINTTerminalRuleCall_2_3_1_0; }
		
		//('minLength' minLength=INT)?
		public Group getGroup_2_4() { return cGroup_2_4; }
		
		//'minLength'
		public Keyword getMinLengthKeyword_2_4_0() { return cMinLengthKeyword_2_4_0; }
		
		//minLength=INT
		public Assignment getMinLengthAssignment_2_4_1() { return cMinLengthAssignment_2_4_1; }
		
		//INT
		public RuleCall getMinLengthINTTerminalRuleCall_2_4_1_0() { return cMinLengthINTTerminalRuleCall_2_4_1_0; }
		
		//('maxLength' maxLength=INT)?
		public Group getGroup_2_5() { return cGroup_2_5; }
		
		//'maxLength'
		public Keyword getMaxLengthKeyword_2_5_0() { return cMaxLengthKeyword_2_5_0; }
		
		//maxLength=INT
		public Assignment getMaxLengthAssignment_2_5_1() { return cMaxLengthAssignment_2_5_1; }
		
		//INT
		public RuleCall getMaxLengthINTTerminalRuleCall_2_5_1_0() { return cMaxLengthINTTerminalRuleCall_2_5_1_0; }
		
		//('pattern' pattern=Text)?
		public Group getGroup_2_6() { return cGroup_2_6; }
		
		//'pattern'
		public Keyword getPatternKeyword_2_6_0() { return cPatternKeyword_2_6_0; }
		
		//pattern=Text
		public Assignment getPatternAssignment_2_6_1() { return cPatternAssignment_2_6_1; }
		
		//Text
		public RuleCall getPatternTextParserRuleCall_2_6_1_0() { return cPatternTextParserRuleCall_2_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_7() { return cRightCurlyBracketKeyword_2_7; }
	}
	public class NumericTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.NumericType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumericTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cDescriptionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_2_1_2_0 = (RuleCall)cDescriptionAssignment_2_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_2_2_0 = (RuleCall)cLocalizationsAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cSizeKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cSizeAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cSizePositiveShortParserRuleCall_2_3_1_0 = (RuleCall)cSizeAssignment_2_3_1.eContents().get(0);
		private final Group cGroup_2_4 = (Group)cGroup_2.eContents().get(4);
		private final Keyword cTotalDigitsKeyword_2_4_0 = (Keyword)cGroup_2_4.eContents().get(0);
		private final Assignment cTotalDigitsAssignment_2_4_1 = (Assignment)cGroup_2_4.eContents().get(1);
		private final RuleCall cTotalDigitsPositiveShortParserRuleCall_2_4_1_0 = (RuleCall)cTotalDigitsAssignment_2_4_1.eContents().get(0);
		private final Group cGroup_2_5 = (Group)cGroup_2.eContents().get(5);
		private final Keyword cFractionDigitsKeyword_2_5_0 = (Keyword)cGroup_2_5.eContents().get(0);
		private final Assignment cFractionDigitsAssignment_2_5_1 = (Assignment)cGroup_2_5.eContents().get(1);
		private final RuleCall cFractionDigitsPositiveShortParserRuleCall_2_5_1_0 = (RuleCall)cFractionDigitsAssignment_2_5_1.eContents().get(0);
		private final Group cGroup_2_6 = (Group)cGroup_2.eContents().get(6);
		private final Keyword cMinInclusiveKeyword_2_6_0 = (Keyword)cGroup_2_6.eContents().get(0);
		private final Assignment cMinInclusiveAssignment_2_6_1 = (Assignment)cGroup_2_6.eContents().get(1);
		private final RuleCall cMinInclusiveDoubleParserRuleCall_2_6_1_0 = (RuleCall)cMinInclusiveAssignment_2_6_1.eContents().get(0);
		private final Group cGroup_2_7 = (Group)cGroup_2.eContents().get(7);
		private final Keyword cMinExclusiveKeyword_2_7_0 = (Keyword)cGroup_2_7.eContents().get(0);
		private final Assignment cMinExclusiveAssignment_2_7_1 = (Assignment)cGroup_2_7.eContents().get(1);
		private final RuleCall cMinExclusiveDoubleParserRuleCall_2_7_1_0 = (RuleCall)cMinExclusiveAssignment_2_7_1.eContents().get(0);
		private final Group cGroup_2_8 = (Group)cGroup_2.eContents().get(8);
		private final Keyword cMaxInclusiveKeyword_2_8_0 = (Keyword)cGroup_2_8.eContents().get(0);
		private final Assignment cMaxInclusiveAssignment_2_8_1 = (Assignment)cGroup_2_8.eContents().get(1);
		private final RuleCall cMaxInclusiveDoubleParserRuleCall_2_8_1_0 = (RuleCall)cMaxInclusiveAssignment_2_8_1.eContents().get(0);
		private final Group cGroup_2_9 = (Group)cGroup_2.eContents().get(9);
		private final Keyword cMaxExclusiveKeyword_2_9_0 = (Keyword)cGroup_2_9.eContents().get(0);
		private final Assignment cMaxExclusiveAssignment_2_9_1 = (Assignment)cGroup_2_9.eContents().get(1);
		private final RuleCall cMaxExclusiveDoubleParserRuleCall_2_9_1_0 = (RuleCall)cMaxExclusiveAssignment_2_9_1.eContents().get(0);
		private final Group cGroup_2_10 = (Group)cGroup_2.eContents().get(10);
		private final Keyword cMeasurementUnitKeyword_2_10_0 = (Keyword)cGroup_2_10.eContents().get(0);
		private final Assignment cMeasurementUnitAssignment_2_10_1 = (Assignment)cGroup_2_10.eContents().get(1);
		private final RuleCall cMeasurementUnitTextParserRuleCall_2_10_1_0 = (RuleCall)cMeasurementUnitAssignment_2_10_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_11 = (Keyword)cGroup_2.eContents().get(11);
		
		//NumericType returns NumericType:
		//    'NumericType'
		//    name=ElementName
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//        ('size' size=PositiveShort)?
		//        ('totalDigits' totalDigits=PositiveShort)?
		//        ('fractionDigits' fractionDigits=PositiveShort)?
		//        ('minInclusive' minInclusive=Double)?
		//        ('minExclusive' minExclusive=Double)?
		//        ('maxInclusive' maxInclusive=Double)?
		//        ('maxExclusive' maxExclusive=Double)?
		//        ('measurementUnit' measurementUnit=Text)?
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'NumericType'
		//name=ElementName
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    ('size' size=PositiveShort)?
		//    ('totalDigits' totalDigits=PositiveShort)?
		//    ('fractionDigits' fractionDigits=PositiveShort)?
		//    ('minInclusive' minInclusive=Double)?
		//    ('minExclusive' minExclusive=Double)?
		//    ('maxInclusive' maxInclusive=Double)?
		//    ('maxExclusive' maxExclusive=Double)?
		//    ('measurementUnit' measurementUnit=Text)?
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'NumericType'
		public Keyword getNumericTypeKeyword_0() { return cNumericTypeKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//    ('size' size=PositiveShort)?
		//    ('totalDigits' totalDigits=PositiveShort)?
		//    ('fractionDigits' fractionDigits=PositiveShort)?
		//    ('minInclusive' minInclusive=Double)?
		//    ('minExclusive' minExclusive=Double)?
		//    ('maxInclusive' maxInclusive=Double)?
		//    ('maxExclusive' maxExclusive=Double)?
		//    ('measurementUnit' measurementUnit=Text)?
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_2_1_0() { return cDescriptionKeyword_2_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_1() { return cLeftParenthesisKeyword_2_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_2_1_2() { return cDescriptionAssignment_2_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_2_1_2_0() { return cDescriptionTextParserRuleCall_2_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_3() { return cRightParenthesisKeyword_2_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_2_2() { return cLocalizationsAssignment_2_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_2_2_0() { return cLocalizationsLocalizationParserRuleCall_2_2_0; }
		
		//('size' size=PositiveShort)?
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//'size'
		public Keyword getSizeKeyword_2_3_0() { return cSizeKeyword_2_3_0; }
		
		//size=PositiveShort
		public Assignment getSizeAssignment_2_3_1() { return cSizeAssignment_2_3_1; }
		
		//PositiveShort
		public RuleCall getSizePositiveShortParserRuleCall_2_3_1_0() { return cSizePositiveShortParserRuleCall_2_3_1_0; }
		
		//('totalDigits' totalDigits=PositiveShort)?
		public Group getGroup_2_4() { return cGroup_2_4; }
		
		//'totalDigits'
		public Keyword getTotalDigitsKeyword_2_4_0() { return cTotalDigitsKeyword_2_4_0; }
		
		//totalDigits=PositiveShort
		public Assignment getTotalDigitsAssignment_2_4_1() { return cTotalDigitsAssignment_2_4_1; }
		
		//PositiveShort
		public RuleCall getTotalDigitsPositiveShortParserRuleCall_2_4_1_0() { return cTotalDigitsPositiveShortParserRuleCall_2_4_1_0; }
		
		//('fractionDigits' fractionDigits=PositiveShort)?
		public Group getGroup_2_5() { return cGroup_2_5; }
		
		//'fractionDigits'
		public Keyword getFractionDigitsKeyword_2_5_0() { return cFractionDigitsKeyword_2_5_0; }
		
		//fractionDigits=PositiveShort
		public Assignment getFractionDigitsAssignment_2_5_1() { return cFractionDigitsAssignment_2_5_1; }
		
		//PositiveShort
		public RuleCall getFractionDigitsPositiveShortParserRuleCall_2_5_1_0() { return cFractionDigitsPositiveShortParserRuleCall_2_5_1_0; }
		
		//('minInclusive' minInclusive=Double)?
		public Group getGroup_2_6() { return cGroup_2_6; }
		
		//'minInclusive'
		public Keyword getMinInclusiveKeyword_2_6_0() { return cMinInclusiveKeyword_2_6_0; }
		
		//minInclusive=Double
		public Assignment getMinInclusiveAssignment_2_6_1() { return cMinInclusiveAssignment_2_6_1; }
		
		//Double
		public RuleCall getMinInclusiveDoubleParserRuleCall_2_6_1_0() { return cMinInclusiveDoubleParserRuleCall_2_6_1_0; }
		
		//('minExclusive' minExclusive=Double)?
		public Group getGroup_2_7() { return cGroup_2_7; }
		
		//'minExclusive'
		public Keyword getMinExclusiveKeyword_2_7_0() { return cMinExclusiveKeyword_2_7_0; }
		
		//minExclusive=Double
		public Assignment getMinExclusiveAssignment_2_7_1() { return cMinExclusiveAssignment_2_7_1; }
		
		//Double
		public RuleCall getMinExclusiveDoubleParserRuleCall_2_7_1_0() { return cMinExclusiveDoubleParserRuleCall_2_7_1_0; }
		
		//('maxInclusive' maxInclusive=Double)?
		public Group getGroup_2_8() { return cGroup_2_8; }
		
		//'maxInclusive'
		public Keyword getMaxInclusiveKeyword_2_8_0() { return cMaxInclusiveKeyword_2_8_0; }
		
		//maxInclusive=Double
		public Assignment getMaxInclusiveAssignment_2_8_1() { return cMaxInclusiveAssignment_2_8_1; }
		
		//Double
		public RuleCall getMaxInclusiveDoubleParserRuleCall_2_8_1_0() { return cMaxInclusiveDoubleParserRuleCall_2_8_1_0; }
		
		//('maxExclusive' maxExclusive=Double)?
		public Group getGroup_2_9() { return cGroup_2_9; }
		
		//'maxExclusive'
		public Keyword getMaxExclusiveKeyword_2_9_0() { return cMaxExclusiveKeyword_2_9_0; }
		
		//maxExclusive=Double
		public Assignment getMaxExclusiveAssignment_2_9_1() { return cMaxExclusiveAssignment_2_9_1; }
		
		//Double
		public RuleCall getMaxExclusiveDoubleParserRuleCall_2_9_1_0() { return cMaxExclusiveDoubleParserRuleCall_2_9_1_0; }
		
		//('measurementUnit' measurementUnit=Text)?
		public Group getGroup_2_10() { return cGroup_2_10; }
		
		//'measurementUnit'
		public Keyword getMeasurementUnitKeyword_2_10_0() { return cMeasurementUnitKeyword_2_10_0; }
		
		//measurementUnit=Text
		public Assignment getMeasurementUnitAssignment_2_10_1() { return cMeasurementUnitAssignment_2_10_1; }
		
		//Text
		public RuleCall getMeasurementUnitTextParserRuleCall_2_10_1_0() { return cMeasurementUnitTextParserRuleCall_2_10_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_11() { return cRightCurlyBracketKeyword_2_11; }
	}
	public class DateTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.DateType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDateTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cDescriptionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_2_1_2_0 = (RuleCall)cDescriptionAssignment_2_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_2_2_0 = (RuleCall)cLocalizationsAssignment_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//DateType returns DateType:
		//    'DateType'
		//    name=ElementName
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'DateType'
		//name=ElementName
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'DateType'
		public Keyword getDateTypeKeyword_0() { return cDateTypeKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_2_1_0() { return cDescriptionKeyword_2_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_1() { return cLeftParenthesisKeyword_2_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_2_1_2() { return cDescriptionAssignment_2_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_2_1_2_0() { return cDescriptionTextParserRuleCall_2_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_3() { return cRightParenthesisKeyword_2_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_2_2() { return cLocalizationsAssignment_2_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_2_2_0() { return cLocalizationsLocalizationParserRuleCall_2_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}
	public class DateTimeTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.DateTimeType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDateTimeTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cDescriptionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_2_1_2_0 = (RuleCall)cDescriptionAssignment_2_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_2_2_0 = (RuleCall)cLocalizationsAssignment_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//DateTimeType returns DateTimeType:
		//    'DateTimeType'
		//    name=ElementName
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'DateTimeType'
		//name=ElementName
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'DateTimeType'
		public Keyword getDateTimeTypeKeyword_0() { return cDateTimeTypeKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_2_1_0() { return cDescriptionKeyword_2_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_1() { return cLeftParenthesisKeyword_2_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_2_1_2() { return cDescriptionAssignment_2_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_2_1_2_0() { return cDescriptionTextParserRuleCall_2_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_3() { return cRightParenthesisKeyword_2_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_2_2() { return cLocalizationsAssignment_2_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_2_2_0() { return cLocalizationsLocalizationParserRuleCall_2_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}
	public class UuidTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.UuidType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUuidTypeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameElementNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftCurlyBracketKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cGroup_2.eContents().get(1);
		private final Keyword cDescriptionKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Assignment cDescriptionAssignment_2_1_2 = (Assignment)cGroup_2_1.eContents().get(2);
		private final RuleCall cDescriptionTextParserRuleCall_2_1_2_0 = (RuleCall)cDescriptionAssignment_2_1_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1_3 = (Keyword)cGroup_2_1.eContents().get(3);
		private final Assignment cLocalizationsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cLocalizationsLocalizationParserRuleCall_2_2_0 = (RuleCall)cLocalizationsAssignment_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//UuidType returns UuidType:
		//    'UuidType'
		//    name=ElementName
		//    ('{'
		//        ('@description' '(' description=Text ')')?
		//        localizations+=Localization*
		//    '}')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'UuidType'
		//name=ElementName
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup() { return cGroup; }
		
		//'UuidType'
		public Keyword getUuidTypeKeyword_0() { return cUuidTypeKeyword_0; }
		
		//name=ElementName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ElementName
		public RuleCall getNameElementNameParserRuleCall_1_0() { return cNameElementNameParserRuleCall_1_0; }
		
		//('{'
		//    ('@description' '(' description=Text ')')?
		//    localizations+=Localization*
		//'}')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2_0() { return cLeftCurlyBracketKeyword_2_0; }
		
		//('@description' '(' description=Text ')')?
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//'@description'
		public Keyword getDescriptionKeyword_2_1_0() { return cDescriptionKeyword_2_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_1_1() { return cLeftParenthesisKeyword_2_1_1; }
		
		//description=Text
		public Assignment getDescriptionAssignment_2_1_2() { return cDescriptionAssignment_2_1_2; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_2_1_2_0() { return cDescriptionTextParserRuleCall_2_1_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1_3() { return cRightParenthesisKeyword_2_1_3; }
		
		//localizations+=Localization*
		public Assignment getLocalizationsAssignment_2_2() { return cLocalizationsAssignment_2_2; }
		
		//Localization
		public RuleCall getLocalizationsLocalizationParserRuleCall_2_2_0() { return cLocalizationsLocalizationParserRuleCall_2_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}
	public class LocalizationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.Localization");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLocalizationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cLocaleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cLocaleIDTerminalRuleCall_1_0 = (RuleCall)cLocaleAssignment_1.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final RuleCall cNameTextParserRuleCall_3_0_0 = (RuleCall)cNameAssignment_3_0.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionTextParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Localization returns Localization:
		//    '@localization'
		//    locale=ID
		//    '('
		//        (name=Text
		//        description=Text?)?
		//    ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'@localization'
		//locale=ID
		//'('
		//    (name=Text
		//    description=Text?)?
		//')'
		public Group getGroup() { return cGroup; }
		
		//'@localization'
		public Keyword getLocalizationKeyword_0() { return cLocalizationKeyword_0; }
		
		//locale=ID
		public Assignment getLocaleAssignment_1() { return cLocaleAssignment_1; }
		
		//ID
		public RuleCall getLocaleIDTerminalRuleCall_1_0() { return cLocaleIDTerminalRuleCall_1_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2() { return cLeftParenthesisKeyword_2; }
		
		//(name=Text
		//description=Text?)?
		public Group getGroup_3() { return cGroup_3; }
		
		//name=Text
		public Assignment getNameAssignment_3_0() { return cNameAssignment_3_0; }
		
		//Text
		public RuleCall getNameTextParserRuleCall_3_0_0() { return cNameTextParserRuleCall_3_0_0; }
		
		//description=Text?
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }
		
		//Text
		public RuleCall getDescriptionTextParserRuleCall_3_1_0() { return cDescriptionTextParserRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
	}
	public class ElementNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.ElementName");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ElementName returns ecore::EString:
		//    STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.Text");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Text returns ecore::EString:
		//    STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	public class UnlimitedNaturalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.UnlimitedNatural");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Keyword cAsteriskKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//UnlimitedNatural returns ecore::EInt:
		//    INT | '*';
		@Override public ParserRule getRule() { return rule; }
		
		//INT | '*'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//'*'
		public Keyword getAsteriskKeyword_1() { return cAsteriskKeyword_1; }
	}
	public class PositiveShortElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.PositiveShort");
		private final RuleCall cINTTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//PositiveShort returns ecore::EShortObject:
		//    INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT
		public RuleCall getINTTerminalRuleCall() { return cINTTerminalRuleCall; }
	}
	public class DoubleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.Double");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//Double returns ecore::EDoubleObject:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	
	public class EntityKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.EntityKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cMASTER_DATAEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cMASTER_DATAMASTER_DATAKeyword_0_0 = (Keyword)cMASTER_DATAEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cREFERENCE_DATAEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cREFERENCE_DATAREFERENCE_DATAKeyword_1_0 = (Keyword)cREFERENCE_DATAEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cABSTRACT_ENTITYEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cABSTRACT_ENTITYABSTRACT_ENTITYKeyword_2_0 = (Keyword)cABSTRACT_ENTITYEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cATTRIBUTE_SETEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cATTRIBUTE_SETATTRIBUTE_SETKeyword_3_0 = (Keyword)cATTRIBUTE_SETEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum EntityKind returns EntityKind:
		//    MASTER_DATA = 'MASTER_DATA' | REFERENCE_DATA = 'REFERENCE_DATA' | ABSTRACT_ENTITY = 'ABSTRACT_ENTITY' | ATTRIBUTE_SET = 'ATTRIBUTE_SET';
		public EnumRule getRule() { return rule; }
		
		//MASTER_DATA = 'MASTER_DATA' | REFERENCE_DATA = 'REFERENCE_DATA' | ABSTRACT_ENTITY = 'ABSTRACT_ENTITY' | ATTRIBUTE_SET = 'ATTRIBUTE_SET'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MASTER_DATA = 'MASTER_DATA'
		public EnumLiteralDeclaration getMASTER_DATAEnumLiteralDeclaration_0() { return cMASTER_DATAEnumLiteralDeclaration_0; }
		
		//'MASTER_DATA'
		public Keyword getMASTER_DATAMASTER_DATAKeyword_0_0() { return cMASTER_DATAMASTER_DATAKeyword_0_0; }
		
		//REFERENCE_DATA = 'REFERENCE_DATA'
		public EnumLiteralDeclaration getREFERENCE_DATAEnumLiteralDeclaration_1() { return cREFERENCE_DATAEnumLiteralDeclaration_1; }
		
		//'REFERENCE_DATA'
		public Keyword getREFERENCE_DATAREFERENCE_DATAKeyword_1_0() { return cREFERENCE_DATAREFERENCE_DATAKeyword_1_0; }
		
		//ABSTRACT_ENTITY = 'ABSTRACT_ENTITY'
		public EnumLiteralDeclaration getABSTRACT_ENTITYEnumLiteralDeclaration_2() { return cABSTRACT_ENTITYEnumLiteralDeclaration_2; }
		
		//'ABSTRACT_ENTITY'
		public Keyword getABSTRACT_ENTITYABSTRACT_ENTITYKeyword_2_0() { return cABSTRACT_ENTITYABSTRACT_ENTITYKeyword_2_0; }
		
		//ATTRIBUTE_SET = 'ATTRIBUTE_SET'
		public EnumLiteralDeclaration getATTRIBUTE_SETEnumLiteralDeclaration_3() { return cATTRIBUTE_SETEnumLiteralDeclaration_3; }
		
		//'ATTRIBUTE_SET'
		public Keyword getATTRIBUTE_SETATTRIBUTE_SETKeyword_3_0() { return cATTRIBUTE_SETATTRIBUTE_SETKeyword_3_0; }
	}
	public class RelationshipKindElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.example.dm.xtext.TextualDataModel.RelationshipKind");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cASSOCIATIONEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cASSOCIATIONASSOCIATIONKeyword_0_0 = (Keyword)cASSOCIATIONEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCOMPOSITIONEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCOMPOSITIONCOMPOSITIONKeyword_1_0 = (Keyword)cCOMPOSITIONEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAGGREGATIONEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAGGREGATIONAGGREGATIONKeyword_2_0 = (Keyword)cAGGREGATIONEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum RelationshipKind returns RelationshipKind:
		//    ASSOCIATION = 'ASSOCIATION' | COMPOSITION = 'COMPOSITION' | AGGREGATION = 'AGGREGATION';
		public EnumRule getRule() { return rule; }
		
		//ASSOCIATION = 'ASSOCIATION' | COMPOSITION = 'COMPOSITION' | AGGREGATION = 'AGGREGATION'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ASSOCIATION = 'ASSOCIATION'
		public EnumLiteralDeclaration getASSOCIATIONEnumLiteralDeclaration_0() { return cASSOCIATIONEnumLiteralDeclaration_0; }
		
		//'ASSOCIATION'
		public Keyword getASSOCIATIONASSOCIATIONKeyword_0_0() { return cASSOCIATIONASSOCIATIONKeyword_0_0; }
		
		//COMPOSITION = 'COMPOSITION'
		public EnumLiteralDeclaration getCOMPOSITIONEnumLiteralDeclaration_1() { return cCOMPOSITIONEnumLiteralDeclaration_1; }
		
		//'COMPOSITION'
		public Keyword getCOMPOSITIONCOMPOSITIONKeyword_1_0() { return cCOMPOSITIONCOMPOSITIONKeyword_1_0; }
		
		//AGGREGATION = 'AGGREGATION'
		public EnumLiteralDeclaration getAGGREGATIONEnumLiteralDeclaration_2() { return cAGGREGATIONEnumLiteralDeclaration_2; }
		
		//'AGGREGATION'
		public Keyword getAGGREGATIONAGGREGATIONKeyword_2_0() { return cAGGREGATIONAGGREGATIONKeyword_2_0; }
	}
	
	private final DataModelElements pDataModel;
	private final EntityElements pEntity;
	private final EntityKindElements eEntityKind;
	private final AttributeElements pAttribute;
	private final RelationshipElements pRelationship;
	private final RelationshipKindElements eRelationshipKind;
	private final RelationshipEndElements pRelationshipEnd;
	private final DataTypeElements pDataType;
	private final BooleanTypeElements pBooleanType;
	private final StringTypeElements pStringType;
	private final NumericTypeElements pNumericType;
	private final DateTypeElements pDateType;
	private final DateTimeTypeElements pDateTimeType;
	private final UuidTypeElements pUuidType;
	private final LocalizationElements pLocalization;
	private final ElementNameElements pElementName;
	private final TextElements pText;
	private final UnlimitedNaturalElements pUnlimitedNatural;
	private final PositiveShortElements pPositiveShort;
	private final DoubleElements pDouble;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TextualDataModelGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDataModel = new DataModelElements();
		this.pEntity = new EntityElements();
		this.eEntityKind = new EntityKindElements();
		this.pAttribute = new AttributeElements();
		this.pRelationship = new RelationshipElements();
		this.eRelationshipKind = new RelationshipKindElements();
		this.pRelationshipEnd = new RelationshipEndElements();
		this.pDataType = new DataTypeElements();
		this.pBooleanType = new BooleanTypeElements();
		this.pStringType = new StringTypeElements();
		this.pNumericType = new NumericTypeElements();
		this.pDateType = new DateTypeElements();
		this.pDateTimeType = new DateTimeTypeElements();
		this.pUuidType = new UuidTypeElements();
		this.pLocalization = new LocalizationElements();
		this.pElementName = new ElementNameElements();
		this.pText = new TextElements();
		this.pUnlimitedNatural = new UnlimitedNaturalElements();
		this.pPositiveShort = new PositiveShortElements();
		this.pDouble = new DoubleElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.example.dm.xtext.TextualDataModel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DataModel returns DataModel:
	//    'DataModel'
	//    name=ElementName
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        ('@locales' '(' locales+=ID* ')' )?
	//        localizations+=Localization*
	//        entities+=Entity*
	//        relationships+=Relationship*
	//        dataTypes+=DataType*
	//    '}')?;
	public DataModelElements getDataModelAccess() {
		return pDataModel;
	}
	
	public ParserRule getDataModelRule() {
		return getDataModelAccess().getRule();
	}
	
	//Entity returns Entity:
	//    'Entity'
	//    name=ElementName
	//    ('[' kind=EntityKind ']')?
	//    ('::' generals+=[Entity|ElementName]+)?
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//        attributes+=Attribute*
	//    '}')?;
	public EntityElements getEntityAccess() {
		return pEntity;
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}
	
	//enum EntityKind returns EntityKind:
	//    MASTER_DATA = 'MASTER_DATA' | REFERENCE_DATA = 'REFERENCE_DATA' | ABSTRACT_ENTITY = 'ABSTRACT_ENTITY' | ATTRIBUTE_SET = 'ATTRIBUTE_SET';
	public EntityKindElements getEntityKindAccess() {
		return eEntityKind;
	}
	
	public EnumRule getEntityKindRule() {
		return getEntityKindAccess().getRule();
	}
	
	//Attribute returns Attribute:
	//    name=ElementName
	//    dataType=[DataType|ElementName]
	//    lower=INT '..' upper=UnlimitedNatural
	//    (identity?='[id]')?
	//    ('defaultValue' '(' defaultValue=Text ')')?
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//    '}')?;
	public AttributeElements getAttributeAccess() {
		return pAttribute;
	}
	
	public ParserRule getAttributeRule() {
		return getAttributeAccess().getRule();
	}
	
	//Relationship returns Relationship:
	//    {Relationship}
	//    'Relationship'
	//    name=ElementName?
	//    ('[' kind=RelationshipKind ']')?
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//        ends+=RelationshipEnd*
	//    '}')?;
	public RelationshipElements getRelationshipAccess() {
		return pRelationship;
	}
	
	public ParserRule getRelationshipRule() {
		return getRelationshipAccess().getRule();
	}
	
	//enum RelationshipKind returns RelationshipKind:
	//    ASSOCIATION = 'ASSOCIATION' | COMPOSITION = 'COMPOSITION' | AGGREGATION = 'AGGREGATION';
	public RelationshipKindElements getRelationshipKindAccess() {
		return eRelationshipKind;
	}
	
	public EnumRule getRelationshipKindRule() {
		return getRelationshipKindAccess().getRule();
	}
	
	//RelationshipEnd returns RelationshipEnd:
	//    name=ElementName?
	//    entity=[Entity|ElementName]
	//    lower=INT '..' upper=UnlimitedNatural
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//    '}')?;
	public RelationshipEndElements getRelationshipEndAccess() {
		return pRelationshipEnd;
	}
	
	public ParserRule getRelationshipEndRule() {
		return getRelationshipEndAccess().getRule();
	}
	
	//DataType returns DataType:
	//    BooleanType | StringType | NumericType | DateType | DateTimeType | UuidType;
	public DataTypeElements getDataTypeAccess() {
		return pDataType;
	}
	
	public ParserRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}
	
	//BooleanType returns BooleanType:
	//    'BooleanType'
	//    name=ElementName
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//    '}')?;
	public BooleanTypeElements getBooleanTypeAccess() {
		return pBooleanType;
	}
	
	public ParserRule getBooleanTypeRule() {
		return getBooleanTypeAccess().getRule();
	}
	
	//StringType returns StringType:
	//    'StringType'
	//    name=ElementName
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//        ('length' length=INT)?
	//        ('minLength' minLength=INT)?
	//        ('maxLength' maxLength=INT)?
	//        ('pattern' pattern=Text)?
	//    '}')?;
	public StringTypeElements getStringTypeAccess() {
		return pStringType;
	}
	
	public ParserRule getStringTypeRule() {
		return getStringTypeAccess().getRule();
	}
	
	//NumericType returns NumericType:
	//    'NumericType'
	//    name=ElementName
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//        ('size' size=PositiveShort)?
	//        ('totalDigits' totalDigits=PositiveShort)?
	//        ('fractionDigits' fractionDigits=PositiveShort)?
	//        ('minInclusive' minInclusive=Double)?
	//        ('minExclusive' minExclusive=Double)?
	//        ('maxInclusive' maxInclusive=Double)?
	//        ('maxExclusive' maxExclusive=Double)?
	//        ('measurementUnit' measurementUnit=Text)?
	//    '}')?;
	public NumericTypeElements getNumericTypeAccess() {
		return pNumericType;
	}
	
	public ParserRule getNumericTypeRule() {
		return getNumericTypeAccess().getRule();
	}
	
	//DateType returns DateType:
	//    'DateType'
	//    name=ElementName
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//    '}')?;
	public DateTypeElements getDateTypeAccess() {
		return pDateType;
	}
	
	public ParserRule getDateTypeRule() {
		return getDateTypeAccess().getRule();
	}
	
	//DateTimeType returns DateTimeType:
	//    'DateTimeType'
	//    name=ElementName
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//    '}')?;
	public DateTimeTypeElements getDateTimeTypeAccess() {
		return pDateTimeType;
	}
	
	public ParserRule getDateTimeTypeRule() {
		return getDateTimeTypeAccess().getRule();
	}
	
	//UuidType returns UuidType:
	//    'UuidType'
	//    name=ElementName
	//    ('{'
	//        ('@description' '(' description=Text ')')?
	//        localizations+=Localization*
	//    '}')?;
	public UuidTypeElements getUuidTypeAccess() {
		return pUuidType;
	}
	
	public ParserRule getUuidTypeRule() {
		return getUuidTypeAccess().getRule();
	}
	
	//Localization returns Localization:
	//    '@localization'
	//    locale=ID
	//    '('
	//        (name=Text
	//        description=Text?)?
	//    ')';
	public LocalizationElements getLocalizationAccess() {
		return pLocalization;
	}
	
	public ParserRule getLocalizationRule() {
		return getLocalizationAccess().getRule();
	}
	
	//ElementName returns ecore::EString:
	//    STRING;
	public ElementNameElements getElementNameAccess() {
		return pElementName;
	}
	
	public ParserRule getElementNameRule() {
		return getElementNameAccess().getRule();
	}
	
	//Text returns ecore::EString:
	//    STRING;
	public TextElements getTextAccess() {
		return pText;
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}
	
	//UnlimitedNatural returns ecore::EInt:
	//    INT | '*';
	public UnlimitedNaturalElements getUnlimitedNaturalAccess() {
		return pUnlimitedNatural;
	}
	
	public ParserRule getUnlimitedNaturalRule() {
		return getUnlimitedNaturalAccess().getRule();
	}
	
	//PositiveShort returns ecore::EShortObject:
	//    INT;
	public PositiveShortElements getPositiveShortAccess() {
		return pPositiveShort;
	}
	
	public ParserRule getPositiveShortRule() {
		return getPositiveShortAccess().getRule();
	}
	
	//Double returns ecore::EDoubleObject:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public DoubleElements getDoubleAccess() {
		return pDouble;
	}
	
	public ParserRule getDoubleRule() {
		return getDoubleAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
