/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TextualDataModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/example/dm/xtext/parser/antlr/internal/InternalTextualDataModel.tokens");
	}
}
