/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class TextualDataModelWebModule extends AbstractTextualDataModelWebModule {
}
