/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class TextualDataModelRuntimeModule extends AbstractTextualDataModelRuntimeModule {

    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return TextualDataModelValueConverterService.class;
    }

}
