/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link TextualDataModelWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractTextualDataModelWebModule extends DefaultWebModule {

}
