/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTextualDataModelScopeProvider extends DelegatingScopeProvider {
}
