/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.example.dm.xtext.services.TextualDataModelGrammarAccess;

@SuppressWarnings("all")
public class TextualDataModelSyntacticSequencer extends AbstractSyntacticSequencer {

	protected TextualDataModelGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Attribute___LeftCurlyBracketKeyword_7_0_RightCurlyBracketKeyword_7_3__q;
	protected AbstractElementAlias match_BooleanType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q;
	protected AbstractElementAlias match_DataModel___LeftCurlyBracketKeyword_2_0___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_DataModel___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q;
	protected AbstractElementAlias match_DateTimeType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q;
	protected AbstractElementAlias match_DateType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q;
	protected AbstractElementAlias match_Entity___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q;
	protected AbstractElementAlias match_NumericType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q;
	protected AbstractElementAlias match_RelationshipEnd___LeftCurlyBracketKeyword_5_0_RightCurlyBracketKeyword_5_3__q;
	protected AbstractElementAlias match_Relationship___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q;
	protected AbstractElementAlias match_StringType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q;
	protected AbstractElementAlias match_UuidType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (TextualDataModelGrammarAccess) access;
		match_Attribute___LeftCurlyBracketKeyword_7_0_RightCurlyBracketKeyword_7_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getAttributeAccess().getLeftCurlyBracketKeyword_7_0()), new TokenAlias(false, false, grammarAccess.getAttributeAccess().getRightCurlyBracketKeyword_7_3()));
		match_BooleanType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getBooleanTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getBooleanTypeAccess().getRightCurlyBracketKeyword_2_3()));
		match_DataModel___LeftCurlyBracketKeyword_2_0___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDataModelAccess().getLeftCurlyBracketKeyword_2_0()), new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDataModelAccess().getLocalesKeyword_2_2_0()), new TokenAlias(false, false, grammarAccess.getDataModelAccess().getLeftParenthesisKeyword_2_2_1()), new TokenAlias(false, false, grammarAccess.getDataModelAccess().getRightParenthesisKeyword_2_2_3())), new TokenAlias(false, false, grammarAccess.getDataModelAccess().getRightCurlyBracketKeyword_2_7()));
		match_DataModel___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDataModelAccess().getLocalesKeyword_2_2_0()), new TokenAlias(false, false, grammarAccess.getDataModelAccess().getLeftParenthesisKeyword_2_2_1()), new TokenAlias(false, false, grammarAccess.getDataModelAccess().getRightParenthesisKeyword_2_2_3()));
		match_DateTimeType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDateTimeTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getDateTimeTypeAccess().getRightCurlyBracketKeyword_2_3()));
		match_DateType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getDateTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getDateTypeAccess().getRightCurlyBracketKeyword_2_3()));
		match_Entity___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getEntityAccess().getLeftCurlyBracketKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getEntityAccess().getRightCurlyBracketKeyword_4_4()));
		match_NumericType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getNumericTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getNumericTypeAccess().getRightCurlyBracketKeyword_2_11()));
		match_RelationshipEnd___LeftCurlyBracketKeyword_5_0_RightCurlyBracketKeyword_5_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRelationshipEndAccess().getLeftCurlyBracketKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getRelationshipEndAccess().getRightCurlyBracketKeyword_5_3()));
		match_Relationship___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRelationshipAccess().getLeftCurlyBracketKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getRelationshipAccess().getRightCurlyBracketKeyword_4_4()));
		match_StringType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getStringTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getStringTypeAccess().getRightCurlyBracketKeyword_2_7()));
		match_UuidType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getUuidTypeAccess().getLeftCurlyBracketKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getUuidTypeAccess().getRightCurlyBracketKeyword_2_3()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Attribute___LeftCurlyBracketKeyword_7_0_RightCurlyBracketKeyword_7_3__q.equals(syntax))
				emit_Attribute___LeftCurlyBracketKeyword_7_0_RightCurlyBracketKeyword_7_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_BooleanType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q.equals(syntax))
				emit_BooleanType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DataModel___LeftCurlyBracketKeyword_2_0___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_DataModel___LeftCurlyBracketKeyword_2_0___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DataModel___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q.equals(syntax))
				emit_DataModel___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DateTimeType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q.equals(syntax))
				emit_DateTimeType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_DateType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q.equals(syntax))
				emit_DateType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Entity___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q.equals(syntax))
				emit_Entity___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_NumericType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q.equals(syntax))
				emit_NumericType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RelationshipEnd___LeftCurlyBracketKeyword_5_0_RightCurlyBracketKeyword_5_3__q.equals(syntax))
				emit_RelationshipEnd___LeftCurlyBracketKeyword_5_0_RightCurlyBracketKeyword_5_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Relationship___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q.equals(syntax))
				emit_Relationship___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_StringType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q.equals(syntax))
				emit_StringType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UuidType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q.equals(syntax))
				emit_UuidType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     defaultValue=Text ')' (ambiguity) (rule end)
	 *     identity?='[id]' (ambiguity) (rule end)
	 *     upper=UnlimitedNatural (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Attribute___LeftCurlyBracketKeyword_7_0_RightCurlyBracketKeyword_7_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_BooleanType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' ('@locales' '(' ')')? '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_DataModel___LeftCurlyBracketKeyword_2_0___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('@locales' '(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     description=Text ')' (ambiguity) '}' (rule end)
	 *     description=Text ')' (ambiguity) dataTypes+=DataType
	 *     description=Text ')' (ambiguity) entities+=Entity
	 *     description=Text ')' (ambiguity) localizations+=Localization
	 *     description=Text ')' (ambiguity) relationships+=Relationship
	 *     name=ElementName '{' (ambiguity) dataTypes+=DataType
	 *     name=ElementName '{' (ambiguity) entities+=Entity
	 *     name=ElementName '{' (ambiguity) localizations+=Localization
	 *     name=ElementName '{' (ambiguity) relationships+=Relationship
	 
	 * </pre>
	 */
	protected void emit_DataModel___LocalesKeyword_2_2_0_LeftParenthesisKeyword_2_2_1_RightParenthesisKeyword_2_2_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_DateTimeType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_DateType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     generals+=[Entity|ElementName] (ambiguity) (rule end)
	 *     kind=EntityKind ']' (ambiguity) (rule end)
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Entity___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_NumericType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_11__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     upper=UnlimitedNatural (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_RelationshipEnd___LeftCurlyBracketKeyword_5_0_RightCurlyBracketKeyword_5_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'Relationship' (ambiguity) (rule start)
	 *     kind=RelationshipKind ']' (ambiguity) (rule end)
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Relationship___LeftCurlyBracketKeyword_4_0_RightCurlyBracketKeyword_4_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_StringType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_7__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('{' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ElementName (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_UuidType___LeftCurlyBracketKeyword_2_0_RightCurlyBracketKeyword_2_3__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
