/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.dm.xtext.ui.internal.XtextActivator;

public class TextualDataModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("org.example.dm.xtext.TextualDataModel");
	}

}
