/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TextualDataModelUiModule extends AbstractTextualDataModelUiModule {

	public TextualDataModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
