/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.example.dm.xtext.ide.contentassist.antlr.internal.InternalTextualDataModelParser;
import org.example.dm.xtext.services.TextualDataModelGrammarAccess;

public class TextualDataModelParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TextualDataModelGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TextualDataModelGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
			builder.put(grammarAccess.getUnlimitedNaturalAccess().getAlternatives(), "rule__UnlimitedNatural__Alternatives");
			builder.put(grammarAccess.getDoubleAccess().getAlternatives_4_0(), "rule__Double__Alternatives_4_0");
			builder.put(grammarAccess.getEntityKindAccess().getAlternatives(), "rule__EntityKind__Alternatives");
			builder.put(grammarAccess.getRelationshipKindAccess().getAlternatives(), "rule__RelationshipKind__Alternatives");
			builder.put(grammarAccess.getDataModelAccess().getGroup(), "rule__DataModel__Group__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_2(), "rule__DataModel__Group_2__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_2_1(), "rule__DataModel__Group_2_1__0");
			builder.put(grammarAccess.getDataModelAccess().getGroup_2_2(), "rule__DataModel__Group_2_2__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_2(), "rule__Entity__Group_2__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_3(), "rule__Entity__Group_3__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_4(), "rule__Entity__Group_4__0");
			builder.put(grammarAccess.getEntityAccess().getGroup_4_1(), "rule__Entity__Group_4_1__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_6(), "rule__Attribute__Group_6__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_7(), "rule__Attribute__Group_7__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup_7_1(), "rule__Attribute__Group_7_1__0");
			builder.put(grammarAccess.getRelationshipAccess().getGroup(), "rule__Relationship__Group__0");
			builder.put(grammarAccess.getRelationshipAccess().getGroup_3(), "rule__Relationship__Group_3__0");
			builder.put(grammarAccess.getRelationshipAccess().getGroup_4(), "rule__Relationship__Group_4__0");
			builder.put(grammarAccess.getRelationshipAccess().getGroup_4_1(), "rule__Relationship__Group_4_1__0");
			builder.put(grammarAccess.getRelationshipEndAccess().getGroup(), "rule__RelationshipEnd__Group__0");
			builder.put(grammarAccess.getRelationshipEndAccess().getGroup_5(), "rule__RelationshipEnd__Group_5__0");
			builder.put(grammarAccess.getRelationshipEndAccess().getGroup_5_1(), "rule__RelationshipEnd__Group_5_1__0");
			builder.put(grammarAccess.getBooleanTypeAccess().getGroup(), "rule__BooleanType__Group__0");
			builder.put(grammarAccess.getBooleanTypeAccess().getGroup_2(), "rule__BooleanType__Group_2__0");
			builder.put(grammarAccess.getBooleanTypeAccess().getGroup_2_1(), "rule__BooleanType__Group_2_1__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup(), "rule__StringType__Group__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup_2(), "rule__StringType__Group_2__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup_2_1(), "rule__StringType__Group_2_1__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup_2_3(), "rule__StringType__Group_2_3__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup_2_4(), "rule__StringType__Group_2_4__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup_2_5(), "rule__StringType__Group_2_5__0");
			builder.put(grammarAccess.getStringTypeAccess().getGroup_2_6(), "rule__StringType__Group_2_6__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup(), "rule__NumericType__Group__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2(), "rule__NumericType__Group_2__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_1(), "rule__NumericType__Group_2_1__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_3(), "rule__NumericType__Group_2_3__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_4(), "rule__NumericType__Group_2_4__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_5(), "rule__NumericType__Group_2_5__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_6(), "rule__NumericType__Group_2_6__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_7(), "rule__NumericType__Group_2_7__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_8(), "rule__NumericType__Group_2_8__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_9(), "rule__NumericType__Group_2_9__0");
			builder.put(grammarAccess.getNumericTypeAccess().getGroup_2_10(), "rule__NumericType__Group_2_10__0");
			builder.put(grammarAccess.getDateTypeAccess().getGroup(), "rule__DateType__Group__0");
			builder.put(grammarAccess.getDateTypeAccess().getGroup_2(), "rule__DateType__Group_2__0");
			builder.put(grammarAccess.getDateTypeAccess().getGroup_2_1(), "rule__DateType__Group_2_1__0");
			builder.put(grammarAccess.getDateTimeTypeAccess().getGroup(), "rule__DateTimeType__Group__0");
			builder.put(grammarAccess.getDateTimeTypeAccess().getGroup_2(), "rule__DateTimeType__Group_2__0");
			builder.put(grammarAccess.getDateTimeTypeAccess().getGroup_2_1(), "rule__DateTimeType__Group_2_1__0");
			builder.put(grammarAccess.getUuidTypeAccess().getGroup(), "rule__UuidType__Group__0");
			builder.put(grammarAccess.getUuidTypeAccess().getGroup_2(), "rule__UuidType__Group_2__0");
			builder.put(grammarAccess.getUuidTypeAccess().getGroup_2_1(), "rule__UuidType__Group_2_1__0");
			builder.put(grammarAccess.getLocalizationAccess().getGroup(), "rule__Localization__Group__0");
			builder.put(grammarAccess.getLocalizationAccess().getGroup_3(), "rule__Localization__Group_3__0");
			builder.put(grammarAccess.getDoubleAccess().getGroup(), "rule__Double__Group__0");
			builder.put(grammarAccess.getDoubleAccess().getGroup_4(), "rule__Double__Group_4__0");
			builder.put(grammarAccess.getDataModelAccess().getNameAssignment_1(), "rule__DataModel__NameAssignment_1");
			builder.put(grammarAccess.getDataModelAccess().getDescriptionAssignment_2_1_2(), "rule__DataModel__DescriptionAssignment_2_1_2");
			builder.put(grammarAccess.getDataModelAccess().getLocalesAssignment_2_2_2(), "rule__DataModel__LocalesAssignment_2_2_2");
			builder.put(grammarAccess.getDataModelAccess().getLocalizationsAssignment_2_3(), "rule__DataModel__LocalizationsAssignment_2_3");
			builder.put(grammarAccess.getDataModelAccess().getEntitiesAssignment_2_4(), "rule__DataModel__EntitiesAssignment_2_4");
			builder.put(grammarAccess.getDataModelAccess().getRelationshipsAssignment_2_5(), "rule__DataModel__RelationshipsAssignment_2_5");
			builder.put(grammarAccess.getDataModelAccess().getDataTypesAssignment_2_6(), "rule__DataModel__DataTypesAssignment_2_6");
			builder.put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
			builder.put(grammarAccess.getEntityAccess().getKindAssignment_2_1(), "rule__Entity__KindAssignment_2_1");
			builder.put(grammarAccess.getEntityAccess().getGeneralsAssignment_3_1(), "rule__Entity__GeneralsAssignment_3_1");
			builder.put(grammarAccess.getEntityAccess().getDescriptionAssignment_4_1_2(), "rule__Entity__DescriptionAssignment_4_1_2");
			builder.put(grammarAccess.getEntityAccess().getLocalizationsAssignment_4_2(), "rule__Entity__LocalizationsAssignment_4_2");
			builder.put(grammarAccess.getEntityAccess().getAttributesAssignment_4_3(), "rule__Entity__AttributesAssignment_4_3");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
			builder.put(grammarAccess.getAttributeAccess().getDataTypeAssignment_1(), "rule__Attribute__DataTypeAssignment_1");
			builder.put(grammarAccess.getAttributeAccess().getLowerAssignment_2(), "rule__Attribute__LowerAssignment_2");
			builder.put(grammarAccess.getAttributeAccess().getUpperAssignment_4(), "rule__Attribute__UpperAssignment_4");
			builder.put(grammarAccess.getAttributeAccess().getIdentityAssignment_5(), "rule__Attribute__IdentityAssignment_5");
			builder.put(grammarAccess.getAttributeAccess().getDefaultValueAssignment_6_2(), "rule__Attribute__DefaultValueAssignment_6_2");
			builder.put(grammarAccess.getAttributeAccess().getDescriptionAssignment_7_1_2(), "rule__Attribute__DescriptionAssignment_7_1_2");
			builder.put(grammarAccess.getAttributeAccess().getLocalizationsAssignment_7_2(), "rule__Attribute__LocalizationsAssignment_7_2");
			builder.put(grammarAccess.getRelationshipAccess().getNameAssignment_2(), "rule__Relationship__NameAssignment_2");
			builder.put(grammarAccess.getRelationshipAccess().getKindAssignment_3_1(), "rule__Relationship__KindAssignment_3_1");
			builder.put(grammarAccess.getRelationshipAccess().getDescriptionAssignment_4_1_2(), "rule__Relationship__DescriptionAssignment_4_1_2");
			builder.put(grammarAccess.getRelationshipAccess().getLocalizationsAssignment_4_2(), "rule__Relationship__LocalizationsAssignment_4_2");
			builder.put(grammarAccess.getRelationshipAccess().getEndsAssignment_4_3(), "rule__Relationship__EndsAssignment_4_3");
			builder.put(grammarAccess.getRelationshipEndAccess().getNameAssignment_0(), "rule__RelationshipEnd__NameAssignment_0");
			builder.put(grammarAccess.getRelationshipEndAccess().getEntityAssignment_1(), "rule__RelationshipEnd__EntityAssignment_1");
			builder.put(grammarAccess.getRelationshipEndAccess().getLowerAssignment_2(), "rule__RelationshipEnd__LowerAssignment_2");
			builder.put(grammarAccess.getRelationshipEndAccess().getUpperAssignment_4(), "rule__RelationshipEnd__UpperAssignment_4");
			builder.put(grammarAccess.getRelationshipEndAccess().getDescriptionAssignment_5_1_2(), "rule__RelationshipEnd__DescriptionAssignment_5_1_2");
			builder.put(grammarAccess.getRelationshipEndAccess().getLocalizationsAssignment_5_2(), "rule__RelationshipEnd__LocalizationsAssignment_5_2");
			builder.put(grammarAccess.getBooleanTypeAccess().getNameAssignment_1(), "rule__BooleanType__NameAssignment_1");
			builder.put(grammarAccess.getBooleanTypeAccess().getDescriptionAssignment_2_1_2(), "rule__BooleanType__DescriptionAssignment_2_1_2");
			builder.put(grammarAccess.getBooleanTypeAccess().getLocalizationsAssignment_2_2(), "rule__BooleanType__LocalizationsAssignment_2_2");
			builder.put(grammarAccess.getStringTypeAccess().getNameAssignment_1(), "rule__StringType__NameAssignment_1");
			builder.put(grammarAccess.getStringTypeAccess().getDescriptionAssignment_2_1_2(), "rule__StringType__DescriptionAssignment_2_1_2");
			builder.put(grammarAccess.getStringTypeAccess().getLocalizationsAssignment_2_2(), "rule__StringType__LocalizationsAssignment_2_2");
			builder.put(grammarAccess.getStringTypeAccess().getLengthAssignment_2_3_1(), "rule__StringType__LengthAssignment_2_3_1");
			builder.put(grammarAccess.getStringTypeAccess().getMinLengthAssignment_2_4_1(), "rule__StringType__MinLengthAssignment_2_4_1");
			builder.put(grammarAccess.getStringTypeAccess().getMaxLengthAssignment_2_5_1(), "rule__StringType__MaxLengthAssignment_2_5_1");
			builder.put(grammarAccess.getStringTypeAccess().getPatternAssignment_2_6_1(), "rule__StringType__PatternAssignment_2_6_1");
			builder.put(grammarAccess.getNumericTypeAccess().getNameAssignment_1(), "rule__NumericType__NameAssignment_1");
			builder.put(grammarAccess.getNumericTypeAccess().getDescriptionAssignment_2_1_2(), "rule__NumericType__DescriptionAssignment_2_1_2");
			builder.put(grammarAccess.getNumericTypeAccess().getLocalizationsAssignment_2_2(), "rule__NumericType__LocalizationsAssignment_2_2");
			builder.put(grammarAccess.getNumericTypeAccess().getSizeAssignment_2_3_1(), "rule__NumericType__SizeAssignment_2_3_1");
			builder.put(grammarAccess.getNumericTypeAccess().getTotalDigitsAssignment_2_4_1(), "rule__NumericType__TotalDigitsAssignment_2_4_1");
			builder.put(grammarAccess.getNumericTypeAccess().getFractionDigitsAssignment_2_5_1(), "rule__NumericType__FractionDigitsAssignment_2_5_1");
			builder.put(grammarAccess.getNumericTypeAccess().getMinInclusiveAssignment_2_6_1(), "rule__NumericType__MinInclusiveAssignment_2_6_1");
			builder.put(grammarAccess.getNumericTypeAccess().getMinExclusiveAssignment_2_7_1(), "rule__NumericType__MinExclusiveAssignment_2_7_1");
			builder.put(grammarAccess.getNumericTypeAccess().getMaxInclusiveAssignment_2_8_1(), "rule__NumericType__MaxInclusiveAssignment_2_8_1");
			builder.put(grammarAccess.getNumericTypeAccess().getMaxExclusiveAssignment_2_9_1(), "rule__NumericType__MaxExclusiveAssignment_2_9_1");
			builder.put(grammarAccess.getNumericTypeAccess().getMeasurementUnitAssignment_2_10_1(), "rule__NumericType__MeasurementUnitAssignment_2_10_1");
			builder.put(grammarAccess.getDateTypeAccess().getNameAssignment_1(), "rule__DateType__NameAssignment_1");
			builder.put(grammarAccess.getDateTypeAccess().getDescriptionAssignment_2_1_2(), "rule__DateType__DescriptionAssignment_2_1_2");
			builder.put(grammarAccess.getDateTypeAccess().getLocalizationsAssignment_2_2(), "rule__DateType__LocalizationsAssignment_2_2");
			builder.put(grammarAccess.getDateTimeTypeAccess().getNameAssignment_1(), "rule__DateTimeType__NameAssignment_1");
			builder.put(grammarAccess.getDateTimeTypeAccess().getDescriptionAssignment_2_1_2(), "rule__DateTimeType__DescriptionAssignment_2_1_2");
			builder.put(grammarAccess.getDateTimeTypeAccess().getLocalizationsAssignment_2_2(), "rule__DateTimeType__LocalizationsAssignment_2_2");
			builder.put(grammarAccess.getUuidTypeAccess().getNameAssignment_1(), "rule__UuidType__NameAssignment_1");
			builder.put(grammarAccess.getUuidTypeAccess().getDescriptionAssignment_2_1_2(), "rule__UuidType__DescriptionAssignment_2_1_2");
			builder.put(grammarAccess.getUuidTypeAccess().getLocalizationsAssignment_2_2(), "rule__UuidType__LocalizationsAssignment_2_2");
			builder.put(grammarAccess.getLocalizationAccess().getLocaleAssignment_1(), "rule__Localization__LocaleAssignment_1");
			builder.put(grammarAccess.getLocalizationAccess().getNameAssignment_3_0(), "rule__Localization__NameAssignment_3_0");
			builder.put(grammarAccess.getLocalizationAccess().getDescriptionAssignment_3_1(), "rule__Localization__DescriptionAssignment_3_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TextualDataModelGrammarAccess grammarAccess;

	@Override
	protected InternalTextualDataModelParser createParser() {
		InternalTextualDataModelParser result = new InternalTextualDataModelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TextualDataModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TextualDataModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
