/*
 * generated by Xtext 2.35.0
 */
package org.example.dm.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class TextualDataModelIdeModule extends AbstractTextualDataModelIdeModule {
}
